### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kosuke-17** [kosuke-17/protospace-34844#1]
http://protospace-34844.herokuapp.com/users/sign_in

**Comment by kinnkann** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログアウト状態のユーザーは、ログイン画面以外のページに遷移できない状況です。**
　→本来、ログアウト状態のユーザーでも、投稿一覧ページや詳細ページに遷移できる必要があります。

修正が完了しましたら、再度以下の報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://docs.google.com/forms/d/e/1FAIpQLSdgFRc0G8WCpE3RuwCDon6yQU_zFA2lH-v04e1mfxdcQr4O0w/viewform

**Comment by kinnkann** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x]  **ログアウト状態のユーザーは、投稿されているプロトタイプの詳細ページにに遷移できません。**
　→本来ログアウト状態のユーザーでも、詳細ページに遷移できる必要があります。詳細を開こうとすると、下記の画面が表示されてしまいます。
<img width="598" alt="スクリーンショット 2021-03-08 12 28 14" src="https://user-images.githubusercontent.com/57080384/110270928-445e6f80-800a-11eb-891f-317b11920931.png">


修正が完了しましたら、再度以下の報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://docs.google.com/forms/d/e/1FAIpQLSdgFRc0G8WCpE3RuwCDon6yQU_zFA2lH-v04e1mfxdcQr4O0w/viewform

**Comment by kinnkann** [comment]
ご提出ありがとうございます！
上記の修正点は解消されていました。ありがとうございます！

再度動作の確認をしたところ、修正していただきたい箇所が3点ございました。
以下のご確認をお願いします！

**【修正依頼箇所】**
◎編集機能周りの修正です。
- [ ] 正しくプロトタイプを編集できた場合は、詳細ページへ遷移するようにしましょう（一覧ページに遷移してしまいます）。
- [ ] バリデーションによって編集ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないようにしましょう。
　→例）「プロトタイプの名称」が空のままで保存ボタンを押すと、記述されていた項目が全て消えてしまいます
- [ ] ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようと
すると、トップページにリダイレクトされるようにしましょう（編集画面に遷移できてしまいます）。

後少しです！応援しています。
修正が完了しましたら、再度以下の報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://docs.google.com/forms/d/e/1FAIpQLSdgFRc0G8WCpE3RuwCDon6yQU_zFA2lH-v04e1mfxdcQr4O0w/viewform

**Comment by kinnkann** [comment]
ご提出ありがとうございます！修正を確認できました！

全て正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう！
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
